-- REMOVE DUPLICATE METER CHANGE
/*
LOGIC:
1. ONLY RUNS FOR COMPANY WISE.
2. ONLY DUPLICATE RECORDS WHERE OLD AND NEW METER NUMBER ARE SAME ARE REMOVED.
3. RUNS FOR ONLY DUPLICATED CONSUMERS.
4. SAVEPOINT ADDED PER CONSUMER.
5. RUNS ONLY FOR THOSE CONSUMERS WHOSE METER CHANGE ENTRY COMES FROM INTERFACE
6. CHANGE "UBIL_TO_UGVCL" MANUALLY ACCORDING TO COMPANY.

*/

DECLARE

  V_BACKUP_CNT NUMBER := 0;
  V_DELETE_CNT NUMBER := 0;

BEGIN
  -- GET DUPLICATE CONSUMERS
  FOR DUP_MTR_CHG IN (
      SELECT G.CONSUMER_NO, COUNT(*) AS CNT
        FROM G11_HHD_FILE_DATA G
       WHERE G.CONSUMER_NO IN (
               SELECT XX.ACCOUNT_NUMBER
                 FROM XXBL_LTCONSUMER_DETAILS@UBIL_TO_UGVCL XX
                WHERE NVL(XX.METER_FLAG, ' ') = 'N'
               
                  AND NVL(XX.METER_CHANGED_FLAG, ' ') = 'Y'
             )
         AND NVL(G.METER_TYPE, ' ') <> 'S'
         AND G.PROCESS_FLAG IS NULL
         AND G.OLD_METER_NO = G.NEW_METER_NO
        -- and G.Consumer_No = '75107010300'
       GROUP BY G.CONSUMER_NO
    --  HAVING COUNT(*) > 1
       ORDER BY G.CONSUMER_NO
  ) LOOP

    BEGIN
      -- SAVEPOINT FOR EACH CONSUMER
      SAVEPOINT SP_DUP_MTR_CHG;

      -- DUPLICATE CONSUMER BACKUP
     /* INSERT INTO G11_BACKUP
        SELECT *
          FROM G11_HHD_FILE_DATA G11
         WHERE G11.CONSUMER_NO = DUP_MTR_CHG.CONSUMER_NO
           AND G11.PROCESS_FLAG IS NULL
           AND G11.OLD_METER_NO = G11.NEW_METER_NO
           AND NVL(G11.METER_TYPE, ' ') <> 'S';*/

      V_BACKUP_CNT := SQL%ROWCOUNT;

      -- DELETE DUPLICATE METER CHANGE RECORDS
      DELETE FROM G11_HHD_FILE_DATA
       WHERE ROWID IN (
             SELECT RID
               FROM (
                     SELECT ROWID RID,
                            ROW_NUMBER() OVER (
                              PARTITION BY CONSUMER_NO
                              ORDER BY UPLOADED_DATE, ROWID
                            ) RN
                       FROM G11_HHD_FILE_DATA G1
                      WHERE G1.PROCESS_FLAG IS NULL
                        AND G1.CONSUMER_NO = DUP_MTR_CHG.CONSUMER_NO
                        AND G1.OLD_METER_NO = G1.NEW_METER_NO
                        AND NVL(G1.METER_TYPE, ' ') <> 'S'
                    )
              WHERE RN >= 1
       );

      V_DELETE_CNT := SQL%ROWCOUNT;

      DBMS_OUTPUT.PUT_LINE('CONSUMER NO : ' || DUP_MTR_CHG.CONSUMER_NO ||
                           ' | BACKUP COUNT : ' || V_BACKUP_CNT ||
                           ' | DELETE COUNT : ' || V_DELETE_CNT);

    EXCEPTION
      WHEN OTHERS THEN
        -- ROLLBACK ONLY CURRENT CONSUMER PROCESS
        ROLLBACK TO SP_DUP_MTR_CHG;

        DBMS_OUTPUT.PUT_LINE('ERROR FOR CONSUMER NO : ' || DUP_MTR_CHG.CONSUMER_NO);
        DBMS_OUTPUT.PUT_LINE('TECHNICAL ERROR : ' || SQLERRM);
        DBMS_OUTPUT.PUT_LINE('ERROR LINE : ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END;

  END LOOP;

  DBMS_OUTPUT.PUT_LINE('PROCESS COMPLETED');

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('PROCESS COMPLETED UNSUCCESSFULLY');
    DBMS_OUTPUT.PUT_LINE('TECHNICAL ERROR : ' || SQLERRM);
    DBMS_OUTPUT.PUT_LINE('ERROR LINE : ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;
/
