-- REVERT SD INTEREST PROCESS LOGIC
-- 1. GET CREATION DATE FROM JOB CHART.
-- 2. DELETE DATA WHERE CREATION_DATE >= LATEST CREATION DATE.
-- 3. UPDATE ROLLBACK FLAG = 'Y' ONLY.
-- 4. SAVEPOINT ADDED.
-- 5. COUNTERS ADDED.


DECLARE
  V_CURR_YEAR       NUMBER := TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'));
  V_CURR_MON        NUMBER := TO_NUMBER(TO_CHAR(SYSDATE, 'MM'));
  V_COM_CODE        NUMBER := 0;
  V_SUBDIV_CHK      NUMBER := 0;
  V_MAX_YER         NUMBER;
  V_MAX_CREA_DATE   DATE;
  V_MAX_MON         NUMBER;

  -- COUNTERS
  V_DEL_DATE_CNT    NUMBER := 0;
  V_DEL_YEAR_CNT    NUMBER := 0;
  V_UPD_LOG_CNT     NUMBER := 0;

  -- INPUT VARIABLES
  P_SUBDIV          NUMBER(3) := &SUBDIV;
  V_FIN_YEAR        VARCHAR2(15) := '&YEAR';

BEGIN
  BEGIN
    -- GET COMPANY CODE FOR THE ENTERED SUBDIVISION
    SELECT DISTINCT SM.COMPANY_CODE
      INTO V_COM_CODE
      FROM SUBDIVISION_MASTER SM
     WHERE SM.SUBDIV_CODE = P_SUBDIV
       AND SM.TO_DT IS NULL;

    IF V_COM_CODE IS NOT NULL THEN
      -- CHECK IF INPUT SUBDIVISION IS VALID
      SELECT COUNT(1)
        INTO V_SUBDIV_CHK
        FROM SUBDIVISION_MASTER SM
       WHERE SM.SUBDIV_CODE = P_SUBDIV
         AND SM.COMPANY_CODE = V_COM_CODE
         AND SM.TO_DT IS NULL;

      IF V_SUBDIV_CHK = 0 THEN
        DBMS_OUTPUT.PUT_LINE('CHECK SUBDIVISION, SUBDIVISION MASTER NOT FOUND OR UNDER OTHER COMPANY.');
        RETURN;
      END IF;
    END IF;

  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('NO DATA FOUND... ENTER CORRECT SUBDIVISION.');
      RETURN;
  END;

  BEGIN
    -- GET LATEST CREATION DATE OF SD INT PROCESS
    SELECT MAX(L.CREATION_DATE)
      INTO V_MAX_CREA_DATE
      FROM SUBDIV_PROCESS_LOG L
     WHERE L.PROCESS_CODE = 'SD_INT_PROCESS'
       AND L.SUBDIV_CODE = P_SUBDIV
       AND L.ROLLBACK_FLAG = 'N';

    -- GET MONTH AND YEAR OF LATEST PROCESS
    SELECT SJC.P_MONTH, SJC.P_YEAR
      INTO V_MAX_MON, V_MAX_YER
      FROM SUBDIV_PROCESS_LOG SJC
     WHERE SJC.SUBDIV_CODE = P_SUBDIV
       AND SJC.PROCESS_CODE = 'SD_INT_PROCESS'
       AND SJC.CREATION_DATE = V_MAX_CREA_DATE
       AND SJC.ROLLBACK_FLAG = 'N';

    IF V_MAX_YER <> V_CURR_YEAR THEN
      DBMS_OUTPUT.PUT_LINE('ONLY CURRENT YEAR ' || V_CURR_YEAR || ' PROCESS IS REVERTED.');
      DBMS_OUTPUT.PUT_LINE('PROCESS IS ALREADY REVERTED OR SD PROCESS NOT RUN YET FOR CURRENT YEAR ' || V_CURR_YEAR || '.');
      RETURN;
    END IF;

  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('NO RECORD FOUND IN JOB CHART, CHECK INPUTS OR PROCESS NOT RUN.');
      RETURN;
  END;

  /********************************************************
                    MAIN DELETION START
  *********************************************************/

  SAVEPOINT SP_SD_INT_REVERT;

  -- DELETE DATE WISE DATA
  DELETE FROM SD_INT_DATE_WISE SDW
   WHERE SDW.SUB_DIV = P_SUBDIV
     AND SDW.FIN_YEAR = V_FIN_YEAR
     AND SDW.CREATION_DATE >= V_MAX_CREA_DATE;

  V_DEL_DATE_CNT := SQL%ROWCOUNT;

  -- DELETE YEAR WISE DATA
  DELETE FROM SD_INT_YEAR_WISE SYW
   WHERE SYW.SUBDIVISION_CODE = P_SUBDIV
     AND SYW.FIN_YEAR = V_FIN_YEAR
     AND SYW.CREATION_DATE >= V_MAX_CREA_DATE;

  V_DEL_YEAR_CNT := SQL%ROWCOUNT;

  -- UPDATE ROLLBACK FLAG IN JOB CHART
  UPDATE SUBDIV_PROCESS_LOG JC
     SET JC.ROLLBACK_FLAG = 'Y'
   WHERE JC.PROCESS_CODE = 'SD_INT_PROCESS'
     AND JC.SUBDIV_CODE = P_SUBDIV
     AND JC.P_MONTH = V_MAX_MON
     AND JC.P_YEAR = V_MAX_YER
     AND JC.CREATION_DATE = V_MAX_CREA_DATE
     AND JC.ROLLBACK_FLAG = 'N';

  V_UPD_LOG_CNT := SQL%ROWCOUNT;

  -- SUCCESS OUTPUT
  DBMS_OUTPUT.PUT_LINE('PROCESS COMPLETED SUCCESSFULLY');
  DBMS_OUTPUT.PUT_LINE('SUBDIVISION        : ' || P_SUBDIV);
  DBMS_OUTPUT.PUT_LINE('FIN YEAR           : ' || V_FIN_YEAR);
  DBMS_OUTPUT.PUT_LINE('PROCESS DATE       : ' || TO_CHAR(V_MAX_CREA_DATE, 'DD-MON-YYYY HH24:MI:SS'));
  DBMS_OUTPUT.PUT_LINE('DATE WISE DELETED  : ' || V_DEL_DATE_CNT);
  DBMS_OUTPUT.PUT_LINE('YEAR WISE DELETED  : ' || V_DEL_YEAR_CNT);
  DBMS_OUTPUT.PUT_LINE('LOG UPDATED        : ' || V_UPD_LOG_CNT);

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK TO SP_SD_INT_REVERT;

    DBMS_OUTPUT.PUT_LINE('PROCESS COMPLETED UNSUCCESSFULLY');
    DBMS_OUTPUT.PUT_LINE('TECHNICAL ERROR: ' || SQLERRM);
    DBMS_OUTPUT.PUT_LINE('ERROR LINE: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;
/
